# Generated by Django 5.1.7 on 2025-04-30 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_blogpost_dislikes_blogpost_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="dislikes_comment", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes_comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
