# Generated by Django 5.1.7 on 2025-04-30 10:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_comment_comment_dislikes_comment_comment_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
