# Generated by Django 5.2 on 2025-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_rename_porfile_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.ManyToManyField(blank=True, to="main.category"),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="intersted_categories", to="main.category"
            ),
        ),
    ]
