# Generated by Django 5.1.7 on 2025-05-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_profile_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pics",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
